START TRANSACTION ;

DROP TABLE IF EXISTS `z42`.`Keys` ;

DROP TABLE IF EXISTS `z42`.`SOA` ;

DROP TABLE IF EXISTS `z42`.`Events` ;

DROP TABLE IF EXISTS `z42`.`ACL` ;

DROP TABLE IF EXISTS `z42`.`Verification` ;

DROP TABLE IF EXISTS `z42`.`RecordSet` ;

DROP TABLE IF EXISTS `z42`.`Location` ;

DROP TABLE IF EXISTS `z42`.`Zone` ;

DROP TABLE IF EXISTS `z42`.`Resource` ;

DROP TABLE IF EXISTS `z42`.`User` ;

COMMIT ;